[book]
language = "en"
multilingual = false
src = "src"
title = "Trin"

[output.html]
additional-js = ["mermaid.min.js", "mermaid-init.js"]
site-url = "/book/"

[output.html.fold]
enable = true

[preprocessor]

[preprocessor.mermaid]
command = "mdbook-mermaid"

