name: book
on:
  push:
    branches: [master]
    paths:
      - 'book/**'
      - 'book.toml'
      - '.github/workflows/book.yml'
  pull_request:
    branches: [master]
    paths:
      - 'book/**'
      - 'book.toml'
      - '.github/workflows/book.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    name: test

    steps:
      - uses: actions/checkout@v3

      - name: Install Rust
        run: bash ci/install-rust.sh stable

      - name: Install mdbook-mermaid
        run: |
          cd book
          cargo install mdbook-mermaid
          mdbook-mermaid install

      - name: Run tests
        run: mdbook test