name: book
on:
  push:
    branches: [master]
    paths:
      - 'book/**'
      - 'book.toml'
      - '.github/workflows/book.yml'
  pull_request:
    branches: [master]
    paths:
      - 'book/**'
      - 'book.toml'
      - '.github/workflows/book.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Rust
        run: |
          rustup set profile minimal
          rustup toolchain install stable
          rustup default stable

      - name: Install mdbook
        run: |
          mkdir bin
          curl -sSL https://github.com/rust-lang/mdBook/releases/download/v0.4.14/mdbook-v0.4.14-x86_64-unknown-linux-gnu.tar.gz | tar -xz --directory=bin
          echo "$(pwd)/bin" >> $GITHUB_PATH

      - name: Run tests
        working-directory: book
        run: mdbook test
  
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Install dependencies
        run: cargo install mdbook
      
      - name: Install mdbook-mermaid
        working-directory: book
        run: |
          cargo install mdbook-mermaid
          mdbook-mermaid install

      - name: Build
        working-directory: book
        run: mdbook build

      - name: Deploy to GitHub Pages
        if: ${{ github.event_name == 'push' }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: book