name: book
on:
  push:
    branches: [master]
    paths:
      - 'book/**'
      - 'book.toml'
      - '.github/workflows/book.yml'
  pull_request:
    branches: [master]
    paths:
      - 'book/**'
      - 'book.toml'
      - '.github/workflows/book.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    name: test

    steps:
      - uses: actions/checkout@v3

      - name: Install mdbook
        run: |
          mkdir mdbook
          curl -sSL https://github.com/rust-lang/mdBook/releases/download/v0.4.14/mdbook-v0.4.14-x86_64-unknown-linux-gnu.tar.gz | tar -xz --directory=./mdbook
          echo `pwd`/mdbook >> $GITHUB_PATH

      - name: Run tests
        run: mdbook test
        working-directory: book

  build:
    runs-on: ubuntu-latest
    name: build

    steps:
      - uses: actions/checkout@v2
      - uses: XAMPPRocky/deploy-mdbook@v1.1
        with:
            token: ${{ secrets.GITHUB_TOKEN }}